[book]
authors = ["secona"]
language = "en"
multilingual = false
src = "src"
title = "seconadotdev-ctf"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css"]

[output.html.fold]
enable = true
